% Help page for the OMP opening menu

global ftm ftz fts;                        

h1 = [''];
h2 = ['  This program will run without any changes, using the default settings'];
h3 = ['  supplied for all necessary input, and produce output based on'];
h4 = ['  the data file testdata.mat supplied with this package.'];
h5 = ['  The Seawater Matlab library of Phil Morgan, CSIRO (Hobart), is required.'];
h6 = ['   For details see the README.ps or README.html files.'];
h7 = [''];
h8 = ['  IMPORTANT: Entries can be made in any order and changed repeatedly as long as'];
h9 = ['  the input buttons are active. Once they are set the buttons turn into display'];
h10 = ['  only, and further changes cannot be made without a restart.'];
h11= [''];
ht1 = str2mat(h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11);
h1= ['  If the status indicator does not return to "waiting for input" this indicates'];
h2= ['  a problem with the last action, for example selection of a non-existing file.'];
h3= ['  The problem can be checked in the Matlab command window. The program can be'];
h4= ['  continued from the graphical user interface by correcting the action. If a'];
h5= ['  correct choice is entered the status display will eventually return to'];
h6= ['  the "waiting for input" message.'];
h7= ['  '];
h8= ['  BUGS: jkarstensen@geomar.de  or  matthias.tomczak@flinders.edu.au'];
ht2 = str2mat(h1,h2,h3,h4,h5,h6,h7,h8);

a = figure('Color',[0.7 0.83 0.8],'MenuBar','none', ...
	'Name','OMP Analysis version 2.0', ...
	'NumberTitle','off','Resize','on', ...
	'Position',[10 20 600 420]);

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7 0.83 0.8], ...
	'ForegroundColor',[1 0 0], ...
	'Position',[0.1 0.85 0.5 0.05], ...
	'HorizontalAlignment','left', ...
	'String','OMP Analysis version 2.0', ...
	'Style','text', ...
	'Tag','StaticText1');
	
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7 0.83 0.8], ...
	'ForegroundColor',[1 0 0], ...
	'Position',[0.6 0.85 0.3 0.05], ...
	'String','by J. Karstensen and M. Tomczak', ...
	'Style','text', ...
	'Tag','StaticText2');

ax = axes('position',[0.05 0.01 0.9 0.84],'color',[0.85 0.95 0.95], ...
	'xcolor',[0.7 0.83 0.8],'ycolor',[0.7 0.83 0.8],'xtick',[],'ytick',[]);
hold on
for i = 1:11
	text(0.1,1.07-0.055*i,ht1(i,:),'color','k','fontname','times','fontsize',ftz);
end

for i = 1:8
	text(0.1,0.47-0.055*i,ht2(i,:),'color','k','fontname',eval(ftm),'fontsize',ftz);
end

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.2], ...
	'Callback','close', ...
	'Position',[0.85 0.05 0.06 0.06], ...
	'String','o.k.', ...
	'Tag','Pushbutton1');
